
import React from 'react';
import { TrendingUp } from 'lucide-react';

interface Props {
  years: number[];
  feeRates: Record<number, number>;
  globalRevenue: number;
  onRateChange: (year: number, rate: number) => void;
  formatCurrency: (amount: number) => string;
}

const FeeSimulator: React.FC<Props> = ({ years, feeRates, globalRevenue, onRateChange, formatCurrency }) => {

  // Calculate total extra revenue over the period using compound logic
  let runningRevenueForTotal = globalRevenue;
  const totalExtraRevenue = years.reduce((acc, year) => {
    const rate = feeRates[year] || 0;
    runningRevenueForTotal = runningRevenueForTotal * (1 + rate / 100);
    const extraForYear = runningRevenueForTotal - globalRevenue;
    return acc + extraForYear;
  }, 0);

  // Helper to track running revenue for display mapping
  let currentRunningRevenue = globalRevenue;

  return (
    <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden flex flex-col">
      <div className="p-4 bg-gradient-to-r from-amber-50 to-orange-50 border-b border-orange-100">
        <div className="flex items-center gap-2 mb-1">
          <div className="p-1.5 bg-orange-100 text-orange-600 rounded-lg">
            <TrendingUp className="w-4 h-4" />
          </div>
          <h3 className="font-bold text-slate-800">Simulation Ecolages</h3>
        </div>
        <p className="text-xs text-slate-600">
          Base revenus: <span className="font-mono font-semibold text-slate-900">{formatCurrency(globalRevenue)}</span>
        </p>
      </div>

      <div className="p-4">
        <div className="space-y-3">
          {years.map(year => {
            const rate = feeRates[year] || 0;
            
            // Compound calculation
            const previousRevenue = currentRunningRevenue;
            currentRunningRevenue = previousRevenue * (1 + rate / 100);
            
            // The "extra" is the difference between the new revenue and the ORIGINAL global revenue baseline
            // representing the additional buying power generated by cumulative increases
            const extraAmount = currentRunningRevenue - globalRevenue;
            
            return (
              <div key={year} className="flex items-center gap-3 text-sm">
                <div className="w-12 font-medium text-slate-500">{year}</div>
                <div className="flex-1 bg-slate-50 rounded-lg p-2 flex items-center gap-2 border border-slate-200 focus-within:border-orange-300 focus-within:ring-2 focus-within:ring-orange-100 transition-all">
                  <input
                    type="number"
                    min="-100"
                    max="100"
                    step="0.1"
                    value={rate}
                    onChange={(e) => onRateChange(year, parseFloat(e.target.value) || 0)}
                    className={`w-12 bg-transparent font-bold text-right outline-none ${rate < 0 ? 'text-red-500' : 'text-slate-800'}`}
                  />
                  <span className="text-slate-400">%</span>
                </div>
                <div className={`w-24 text-right font-mono font-medium text-xs sm:text-sm ${extraAmount >= 0 ? 'text-orange-600' : 'text-red-500'}`}>
                  {extraAmount > 0 ? '+' : ''}{formatCurrency(extraAmount)}
                </div>
              </div>
            );
          })}
        </div>

        <div className="mt-4 pt-3 border-t border-slate-100">
            <div className="flex justify-between items-center px-1">
            <span className="text-sm font-medium text-slate-600">Cumul généré</span>
            <span className={`font-bold text-lg ${totalExtraRevenue >= 0 ? 'text-orange-600' : 'text-red-600'}`}>
                {formatCurrency(totalExtraRevenue)}
            </span>
            </div>
        </div>
      </div>
    </div>
  );
};

export default FeeSimulator;